apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel | quote }}
            - name: API_URL
              value: {{ .Values.env.apiUrl | quote }}
            - name: CUDA_API_URL
              value: {{ .Values.env.cudaApiUrl | quote }}
            - name: COMPLETED_PATH
              value: {{ .Values.env.completedPath | quote }}
            - name: SOURCE_PATH
              value: {{ .Values.env.sourcePath | quote }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env-secrets
          {{- if .Values.nfs.enabled }}
          volumeMounts:
            - name: {{ .Values.nfs.name }}
              mountPath: {{ .Values.nfs.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nfs.enabled }}
      volumes:
        - name: {{ .Values.nfs.name }}
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
      {{- end }}
