apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.logLevel | quote }}
            - name: API_URL
              value: {{ .Values.env.apiUrl | quote }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
