apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-env-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameter-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-env-secrets
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: /k8s/ender-bot/discord_token
    - secretKey: DM_CHANNEL
      remoteRef:
        key: /k8s/ender-bot/dm_channel
    - secretKey: PLAYER_CHANNEL
      remoteRef:
        key: /k8s/ender-bot/player_channel