replicaCount: 1

image:
  repository: mawhaze/ender_bot
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

env:
  logLevel: DEBUG
  apiUrl: https://attdm.staging.mawhaze.dev

imagePullSecrets:
  - name: docker-auth

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
