replicaCount: 1

image:
  repository: mawhaze/ender_bot
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

env:
  logLevel: DEBUG
  apiUrl: https://attdm.staging.mawhaze.dev
  cudaApiUrl: http://kubeai/openai/v1/audio/transcriptions
  sourcePath: /mnt/transcribe/source
  completedPath: /mnt/transcribe/completed
  transcribeDir: /mnt/transcribe/tmp


imagePullSecrets:
  - name: docker-auth-secret

nfs:
  enabled: true
  name: "ender-bot-nfs"
  mountPath: /mnt/transcribe
  path: /mnt/ZPool01/media/transcribe
  server: 10.10.10.20

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
